services:
  ###############################################################################
  # Valkey (Redis-compatible)
  ###############################################################################
  valkey:
    image: valkey/valkey:7.2-bookworm
    environment:
      VALKEY_PORT: ${VALKEY_PORT:-6379}
    expose:
      - '6379'
    volumes:
      - ./data/valkey:/data
    command: [
        'sh',
        '-c',
        'docker-entrypoint.sh --requirepass ${VALKEY_PASSWORD} --loglevel warning'
      ]
    networks:
      - net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${VALKEY_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ###############################################################################
  # Mongo
  ###############################################################################
  mongo:
    image: mongo:7
    environment:
      MONGO_PORT: ${MONGO_PORT:-27017}
    command: mongod --quiet --logpath /dev/null --wiredTigerCacheSizeGB 1
    expose:
      - '27017'
    volumes:
      - ./data/mongodb:/data/db
      - ./backup:/backup
    networks:
      - net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

###############################################################################
# Networks
###############################################################################
networks:
  net:
    driver: bridge