version: '3'

services:
  ###############################################################################
  # Redis
  ###############################################################################
  redis:
    image: redis:7.4-bookworm
    environment:
      REDIS_PORT: 6379
    expose:
      - '6379'
    volumes:
      - ./data/redis:/data
    command: [
        'sh',
        '-c',
        'docker-entrypoint.sh --requirepass redis_password --loglevel warning'
      ]
    networks:
      - net

  ###############################################################################
  # Mongo
  ###############################################################################
  mongo:
    image: mongo:7
    environment:
      MONGO_PORT: 27017
    command: --quiet --logpath /dev/null
    expose:
      - '27017'
    volumes:
      - ./data/mongodb:/data/db
      - ./backup:/backup
    networks:
      - net

  ###############################################################################
  # Gateway
  ###############################################################################
  gateway:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/gateway:latest'
    environment:
      NODE_ENV: production
      LOGGER_LEVEL: info
      PORT: 8080
      EXPOSE_FRONTENDS: 'true'
      AUTHENTICATOR_URL: http://authenticator:8000
      API_URL: http://api:8200/api/v2
      PDFGENERATOR_URL: http://pdfgenerator:8300/pdfgenerator
      EMAILER_URL: http://emailer:8400/emailer
      LANDLORD_FRONTEND_URL: http://landlord-frontend:8180
      LANDLORD_BASE_PATH: /landlord
      TENANT_FRONTEND_URL: http://tenant-frontend:8190
      TENANT_BASE_PATH: /tenant
      APP_DOMAIN: localhost:8080
      CORS_ENABLED: 'true'
      TENANTAPI_URL: http://tenantapi:8250/tenantapi
    ports:
      - '8080:8080'
    networks:
      - net
    depends_on:
      - authenticator
      - api
      - tenantapi
      - pdfgenerator
      - emailer

  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/authenticator:latest'
    environment:
      NODE_ENV: production
      PORT: 8000
      LOGGER_LEVEL: info
      REDIS_URL: redis://redis
      REDIS_PASSWORD: redis_password
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret
      RESET_TOKEN_SECRET: reset_token_secret
      APPCREDZ_TOKEN_SECRET: appcredz_token_secret
      MONGO_URL: mongodb://mongo/mredb
      EMAILER_URL: http://emailer:8400/emailer
      SIGNUP: 'true'
      APP_DOMAIN: localhost
      APP_PROTOCOL: http
    expose:
      - '8000'
    networks:
      - net
    depends_on:
      - redis
      - mongo
      - emailer

  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/pdfgenerator:latest'
    environment:
      NODE_ENV: production
      PORT: 8300
      LOGGER_LEVEL: info
      MONGO_URL: mongodb://mongo/mredb
      ACCESS_TOKEN_SECRET: access_token_secret
      CIPHER_KEY: cipher_key
      CIPHER_IV_KEY: cipher_iv_key
      UPLOAD_MAX_SIZE: 2000000000
    expose:
      - '8300'
    networks:
      - net
    depends_on:
      - mongo

  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/emailer:latest'
    environment:
      NODE_ENV: production
      ALLOW_SENDING_EMAILS: 'true'
      PORT: 8400
      LOGGER_LEVEL: info
      LANDLORD_APP_URL: http://localhost:8080/landlord
      TENANT_APP_URL: http://localhost:8080/tenant
      MONGO_URL: mongodb://mongo/mredb
      ACCESS_TOKEN_SECRET: access_token_secret
      CIPHER_KEY: cipher_key
      CIPHER_IV_KEY: cipher_iv_key
      PDFGENERATOR_URL: http://pdfgenerator:8300/pdfgenerator
      EMAIL_FROM: "MicroRealEstate <noreply@example.com>"
      EMAIL_REPLY_TO: support@example.com
    expose:
      - '8400'
    networks:
      - net
    depends_on:
      - mongo
      - pdfgenerator

  ###############################################################################
  # api
  ###############################################################################
  api:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/api:latest'
    volumes:
      - ./backup:/usr/app/backup
    environment:
      NODE_ENV: production
      PORT: 8200
      LOGGER_LEVEL: info
      MONGO_URL: mongodb://mongo/mredb
      EMAILER_URL: http://emailer:8400/emailer
      PDFGENERATOR_URL: http://pdfgenerator:8300/pdfgenerator
      RESTORE_DB: 'false'
      ACCESS_TOKEN_SECRET: access_token_secret
      CIPHER_KEY: cipher_key
      CIPHER_IV_KEY: cipher_iv_key
    expose:
      - '8200'
    networks:
      - net
    depends_on:
      - mongo
      - emailer
      - pdfgenerator

  ###############################################################################
  # tenant api
  ###############################################################################
  tenantapi:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/tenantapi:latest'
    environment:
      NODE_ENV: production
      PORT: 8250
      LOGGER_LEVEL: info
      MONGO_URL: mongodb://mongo/mredb
      ACCESS_TOKEN_SECRET: access_token_secret
    expose:
      - '8250'
    networks:
      - net
    depends_on:
      - mongo

  ###############################################################################
  # Landlord frontend
  ###############################################################################
  landlord-frontend:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/landlord-frontend:latest'
    environment:
      BASE_PATH: /landlord
      PORT: 8180
      DOCKER_GATEWAY_URL: http://gateway:8080
      CORS_ENABLED: 'true'
      GATEWAY_URL: http://localhost:8080
      NODE_ENV: production
      SIGNUP: 'true'
    expose:
      - '8180'
    networks:
      - net
    depends_on:
      - gateway

  ###############################################################################
  # Tenant frontend
  ###############################################################################
  tenant-frontend:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/tenant-frontend:latest'
    environment:
      BASE_PATH: /tenant
      PORT: 8190
      DOCKER_GATEWAY_URL: http://gateway:8080
      CORS_ENABLED: 'true'
      GATEWAY_URL: http://localhost:8080
      NODE_ENV: production
    expose:
      - '8190'
    networks:
      - net
    depends_on:
      - gateway

###############################################################################
# microservices network
###############################################################################
networks:
  net:
    driver: bridge
