name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.2.3)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    outputs:
      version: ${{ steps.version.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Version: ${VERSION}"

    - name: Generate changelog
      id: changelog
      run: |
        # Generate changelog from git commits since last tag
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        if [ -n "$LAST_TAG" ]; then
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" ${LAST_TAG}..HEAD)
        else
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" --max-count=20)
        fi
        
        # Save changelog to file
        cat > CHANGELOG.md << EOF
        # Release ${{ steps.version.outputs.version }}
        
        ## What's Changed
        
        ${CHANGELOG}
        
        ## Docker Images
        
        All microservices are available as Docker images:
        
        - \`ghcr.io/${{ github.repository }}/api:${{ steps.version.outputs.version }}\`
        - \`ghcr.io/${{ github.repository }}/authenticator:${{ steps.version.outputs.version }}\`
        - \`ghcr.io/${{ github.repository }}/emailer:${{ steps.version.outputs.version }}\`
        - \`ghcr.io/${{ github.repository }}/gateway:${{ steps.version.outputs.version }}\`
        - \`ghcr.io/${{ github.repository }}/landlord-frontend:${{ steps.version.outputs.version }}\`
        - \`ghcr.io/${{ github.repository }}/pdfgenerator:${{ steps.version.outputs.version }}\`
        - \`ghcr.io/${{ github.repository }}/tenant-frontend:${{ steps.version.outputs.version }}\`
        - \`ghcr.io/${{ github.repository }}/tenantapi:${{ steps.version.outputs.version }}\`
        - \`ghcr.io/${{ github.repository }}/whatsapp:${{ steps.version.outputs.version }}\`
        
        ## Installation
        
        \`\`\`bash
        # Download the latest docker-compose.yml
        curl -O https://raw.githubusercontent.com/${{ github.repository }}/${{ steps.version.outputs.version }}/docker-compose.yml
        
        # Start the application
        docker compose --profile local up -d
        \`\`\`
        
        ## Features
        
        -  Complete property management system
        -  WhatsApp integration for notifications and OTP authentication
        -  Multi-language support (EN, ES, FR, DE, PT)
        -  Enhanced security with JWT and rate limiting
        -  Modern UI with shadcn/ui components
        -  Full Docker containerization
        -  Microservices architecture
        EOF

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: MicroRealEstate ${{ steps.version.outputs.version }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false

  create-deployment-package:
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create deployment package
      run: |
        mkdir -p deployment-package
        
        # Copy essential files
        cp docker-compose.yml deployment-package/
        cp .env.domain deployment-package/.env.example
        cp README.md deployment-package/
        
        # Create installation script
        cat > deployment-package/install.sh << 'EOF'
        #!/bin/bash
        set -e
        
        echo " Installing MicroRealEstate ${{ needs.create-release.outputs.version }}"
        echo ""
        
        # Check if Docker is installed
        if ! command -v docker &> /dev/null; then
            echo " Docker is not installed. Please install Docker first."
            exit 1
        fi
        
        # Check if Docker Compose is installed
        if ! command -v docker compose &> /dev/null; then
            echo " Docker Compose is not installed. Please install Docker Compose first."
            exit 1
        fi
        
        # Create .env file if it doesn't exist
        if [ ! -f .env ]; then
            echo " Creating .env file from template..."
            cp .env.example .env
            echo "  Please edit the .env file and configure your secrets and tokens!"
            echo "   Required: JWT_SECRET, CIPHER_KEY, CIPHER_IV_KEY"
            echo "   Optional: WhatsApp, Email, and other service configurations"
            echo ""
        fi
        
        echo " Starting MicroRealEstate..."
        docker compose --profile local up -d
        
        echo ""
        echo " MicroRealEstate is starting up!"
        echo ""
        echo " Access your application at:"
        echo "   Landlord Interface: http://localhost:8080/landlord"
        echo "   Tenant Interface: http://localhost:8080/tenant"
        echo ""
        echo " Check status with: docker compose --profile local ps"
        echo " View logs with: docker compose --profile local logs -f"
        EOF
        
        chmod +x deployment-package/install.sh
        
        # Create archive
        tar -czf microrealestate-${{ needs.create-release.outputs.version }}.tar.gz -C deployment-package .

    - name: Upload deployment package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./microrealestate-${{ needs.create-release.outputs.version }}.tar.gz
        asset_name: microrealestate-${{ needs.create-release.outputs.version }}.tar.gz
        asset_content_type: application/gzip

  notify-completion:
    needs: [create-release, create-deployment-package]
    runs-on: ubuntu-latest
    steps:
    - name: Release Summary
      run: |
        echo " Release ${{ needs.create-release.outputs.version }} completed successfully!"
        echo ""
        echo " Docker Images will be built by the Docker Images workflow"
        echo " Release package: microrealestate-${{ needs.create-release.outputs.version }}.tar.gz"
        echo ""
        echo " Ready for production deployment!"
